FidelCly/dashboard

package-lock.json, package.json
fix off the dependabot auto merge failing due to a missing package during action build (react-router-dom)
the package seem to have been supress during a git conflic.
[FID-]
=> fix: re-add react router dom(git conflic fix)

src/pages/auth/signin.tsx
- fix the redirection on shop create on the login
=> Fix: login redirection

src/Components/html/Navbar.tsx, src/pages/api/promotions/[id].ts, src/pages/api/promotions/index.ts, src/pages/api/shop/[id]/promotion.ts, src/pages/campagne/index.tsx, src/pages/scanner/index.tsx, src/pages/settings/index.tsx, src/test/Components/form/PromotionCreateForm.cy.tsx
=> fix: build

src/Components/scanner.tsx, src/pages/campagne/[id]/edit.tsx, src/pages/me/index.tsx, src/pages/promotion/[id]/edit.tsx, src/pages/scanner/index.tsx, src/pages/shops/[id]/edit.tsx, src/pages/shops/create.tsx
- *describe your work here ...*
- 
-
[FID-]
=> fix: css for edit pages

src/Components/List/PromotionList.tsx
- add delete promotion to promotion page
=> feat : add delete promotion

src/Components/auth/Profile.tsx, src/pages/me/index.tsx, src/pages/promotion/index.tsx
- fix user profile due to api call change
=> fix: profile route

src/Components/scanner.tsx
- add api message in checkout toast
=> feat: add checkout message

src/Components/List/CampaignList.tsx, src/Components/form/Campaign.form.tsx, src/pages/api/campaign/send.ts, src/pages/campagne/[id]/edit.tsx, src/pages/campagne/index.tsx
- add send campaing to page
- add delete campaing to page
=> feat: add send campaign

src/Components/form/Campaign.form.tsx, src/Components/form/Promotion.form.tsx, src/Components/form/Shop.form.tsx, src/pages/auth/signin.tsx, src/pages/auth/signup.tsx
- form validation errors
[FID-179]
[FID-179]: https://msc-etna.atlassian.net/browse/FID-179?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: form validation errors

src/components/form/Campaign.form.tsx
- remove maxLength from textarea & set rows at 10
- 
-
[FID-]
=> fix: remove maxLength from textarea & set rows at 10

src/components/form/Shop.form.tsx
- remove maxLength from google address
- 
-
[FID-]
=> fix: remove maxLength from google address

src/components/form/User.form.tsx, src/models/User.ts, src/pages/settings/index.tsx
- add email on user update form
- 
-
[FID-189]
[FID-189]: https://msc-etna.atlassian.net/browse/FID-189?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: add email on user update form

src/components/form/Promotion.form.tsx, src/components/list/PromotionList.tsx
- date format && display of inactive promotions
- 
-
[FID-190]
[FID-190]: https://msc-etna.atlassian.net/browse/FID-190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: date format && display of inactive promotions

src/components/form/Campaign.form.tsx, src/components/form/Promotion.form.tsx, src/components/form/Shop.form.tsx, src/components/form/User.form.tsx, src/components/list/CampaignList.tsx, src/components/list/PromotionList.tsx, src/components/scanner.tsx, src/pages/auth/signin.tsx, src/pages/auth/signup.tsx, src/translation.ts
-  translation and remove console logs
- 
-
[FID-]
=> fix: translation and remove console logs

src/components/form/Shop.form.tsx, src/components/layout/Navbar.tsx, src/models/Shop.ts
- add shop picture and display on navbar and settings
- 
-
[FID-188]
[FID-188]: https://msc-etna.atlassian.net/browse/FID-188?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add shop picture and display on navbar and settings

src/components/form/Shop.form.tsx, src/components/form/User.form.tsx, src/models/User.ts, src/pages/settings/index.tsx
-  add picture profile on user form and navbar
- 
-
[FID-194]
[FID-194]: https://msc-etna.atlassian.net/browse/FID-194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: add picture profile on user form and navbar

src/components/layout/Sidebar.tsx
=> fix: remove li

src/components/form/Campaign.form.tsx, src/components/list/CardsList.tsx, src/components/list/PromotionList.tsx, src/models/Balance.ts, src/models/Card.ts, src/pages/api/shop/[id]/cards.ts, src/pages/index.tsx, src/pages/settings/index.tsx
- add recent activity on analytics
- 
-
[FID-]
=> feat: add recent activity on analytics

src/components/list/CampaignList.tsx, src/components/list/CardsList.tsx, src/components/list/PromotionList.tsx
=> feat: use states

src/components/form/Campaign.form.tsx, src/components/form/Promotion.form.tsx, src/components/form/Shop.form.tsx, src/components/form/User.form.tsx, src/components/layout/Navbar.tsx, src/components/list/CampaignList.tsx, src/components/list/CardsList.tsx, src/components/list/PromotionList.tsx, src/components/scanner.tsx, src/pages/index.tsx
- add animations and refactor css
- 
-
[FID-]
=> feat: add animations and refactor css

src/components/form/Campaign.form.tsx, src/components/form/Promotion.form.tsx, src/components/list/CampaignList.tsx, src/components/list/PromotionList.tsx, src/models/Campaign.ts, src/models/Promotions.ts, src/pages/auth/signin.tsx, src/pages/campaign/index.tsx, src/pages/promotion/index.tsx, src/test/Components/form/PromotionCreateForm.cy.tsx, src/test/Components/list/PromotionList.cy.tsx
-  use states for lists management
- 
-
[FID-]
=> feat: use states for lists management

src/components/form/Promotion.form.tsx
- add pattern to validate checkout limit
- 
-
[FID-207]
[FID-207]: https://msc-etna.atlassian.net/browse/FID-207?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: add pattern to validate checkout limit

src/components/form/Campaign.form.tsx, src/components/form/User.form.tsx
- display select with correct value on edit forms
- 
-
[FID-206]
[FID-206]: https://msc-etna.atlassian.net/browse/FID-206?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: display select with correct value on edit forms

src/components/list/CardsList.tsx
- sort condition on activity
- 
-
[FID-202]
[FID-202]: https://msc-etna.atlassian.net/browse/FID-202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: sort condition on activity

package-lock.json, package.json, pnpm-lock.yaml, src/components/list/CampaignList.tsx, src/components/list/CardsList.tsx, src/components/list/PromotionList.tsx
- add luxen and set in french
- 
-
[FID-200]
[FID-200]: https://msc-etna.atlassian.net/browse/FID-200?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: add luxen and set in french

src/components/scanner.tsx
- add error message
- 
-
[FID-201]
[FID-201]: https://msc-etna.atlassian.net/browse/FID-201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: add error message

next.config.js, src/components/layout/Navbar.tsx, src/components/list/CampaignList.tsx, src/components/list/CardsList.tsx, src/components/list/PromotionList.tsx, src/pages/index.tsx
=> refactor: skeleton

src/components/scanner.tsx
- display username when scanning a qrcode
- 
-
[FID-]
=> feat: display username when scanning a qrcode

src/components/form/Shop.form.tsx
- select activity on update form
- 
-
[FID-208]
[FID-208]: https://msc-etna.atlassian.net/browse/FID-208?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: select activity on update form

src/components/layout/Navbar.tsx, src/components/layout/Sidebar.tsx, src/components/list/CardsList.tsx, src/components/scanner.tsx, src/pages/_app.tsx, src/pages/auth/signin.tsx, src/pages/auth/signup.tsx, src/pages/campaign/index.tsx, src/pages/index.tsx, src/pages/scanner/index.tsx, src/pages/settings/index.tsx
- add responsiveness to all pages
- 
-
[FID-]
=> feat: add responsiveness to all pages
